name: CI

on:
  push:
  pull_request:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v5
      - name: Run ShellCheck
        uses: https://github.com/ludeeus/action-shellcheck@master
        with:
          scandir: .
          check_together: 'yes'

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://github.com/actions/checkout@v5
      - uses: https://github.com/dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Run tests
        run: cargo test
      - name: Run clippy
        run: cargo clippy
