#!/bin/bash
# Copyright: Christoph Dittmann <eigene_homepage@gmx.de>
# License: GNU GPL, version 3 or later; http://www.gnu.org/copyleft/gpl.html
#
# Katakana trainer.

DIRECTORY="."
KANA_FILE="$DIRECTORY/katakana.txt"
IRC_COMMAND='!kata'

. ./kana
